#employees =
[
  {"eid": 1, "ename": "Amitabh Bachchan", "gender": "M"},
  {"eid": 2, "ename": "Shah Rukh Khan", "gender": "M"},
  {"eid": 3, "ename": "Salman Khan", "gender": "M"},
  {"eid": 4, "ename": "Aamir Khan", "gender": "M"},
  {"eid": 5, "ename": "Akshay Kumar", "gender": "M"},
  {"eid": 6, "ename": "Ajay Devgn", "gender": "M"},
  {"eid": 7, "ename": "Hrithik Roshan", "gender": "M"},
  {"eid": 8, "ename": "Ranbir Kapoor", "gender": "M"},
  {"eid": 9, "ename": "Ranveer Singh", "gender": "M"},
  {"eid": 10, "ename": "Kartik Aaryan", "gender": "M"},
  {"eid": 11, "ename": "Rajinikanth", "gender": "M"},
  {"eid": 12, "ename": "Kamal Haasan", "gender": "M"},
  {"eid": 13, "ename": "Vijay", "gender": "M"},
  {"eid": 14, "ename": "Ajith Kumar", "gender": "M"},
  {"eid": 15, "ename": "Suriya", "gender": "M"},
  {"eid": 16, "ename": "Dhanush", "gender": "M"},
  {"eid": 17, "ename": "Vikram", "gender": "M"},
  {"eid": 18, "ename": "Prabhas", "gender": "M"},
  {"eid": 19, "ename": "Mahesh Babu", "gender": "M"},
  {"eid": 20, "ename": "Allu Arjun", "gender": "M"},
  {"eid": 21, "ename": "Ram Charan", "gender": "M"},
  {"eid": 22, "ename": "Jr NTR", "gender": "M"},
  {"eid": 23, "ename": "Pawan Kalyan", "gender": "M"},
  {"eid": 24, "ename": "Chiranjeevi", "gender": "M"},
  {"eid": 25, "ename": "Nagarjuna", "gender": "M"},
  {"eid": 26, "ename": "Venkatesh", "gender": "M"},
  {"eid": 27, "ename": "Balakrishna", "gender": "M"},
  {"eid": 28, "ename": "Ravi Teja", "gender": "M"},
  {"eid": 29, "ename": "Nani", "gender": "M"},
  {"eid": 30, "ename": "Vijay Deverakonda", "gender": "M"},
  {"eid": 31, "ename": "Deepika Padukone", "gender": "F"},
  {"eid": 32, "ename": "Alia Bhatt", "gender": "F"},
  {"eid": 33, "ename": "Kareena Kapoor", "gender": "F"},
  {"eid": 34, "ename": "Priyanka Chopra", "gender": "F"},
  {"eid": 35, "ename": "Katrina Kaif", "gender": "F"},
  {"eid": 36, "ename": "Anushka Sharma", "gender": "F"},
  {"eid": 37, "ename": "Sonam Kapoor", "gender": "F"},
  {"eid": 38, "ename": "Jacqueline Fernandez", "gender": "F"},
  {"eid": 39, "ename": "Kriti Sanon", "gender": "F"},
  {"eid": 40, "ename": "Taapsee Pannu", "gender": "F"},
  {"eid": 41, "ename": "Rashmika Mandanna", "gender": "F"},
  {"eid": 42, "ename": "Samantha Ruth Prabhu", "gender": "F"},
  {"eid": 43, "ename": "Nayanthara", "gender": "F"},
  {"eid": 44, "ename": "Trisha Krishnan", "gender": "F"},
  {"eid": 45, "ename": "Keerthy Suresh", "gender": "F"},
  {"eid": 46, "ename": "Sai Pallavi", "gender": "F"},
  {"eid": 47, "ename": "Pooja Hegde", "gender": "F"},
  {"eid": 48, "ename": "Tamannaah Bhatia", "gender": "F"},
  {"eid": 49, "ename": "Ileana D'Cruz", "gender": "F"},
  {"eid": 50, "ename": "Anushka Shetty", "gender": "F"},
  {"eid": 51, "ename": "Madhuri Dixit", "gender": "F"},
  {"eid": 52, "ename": "Sridevi", "gender": "F"},
  {"eid": 53, "ename": "Juhi Chawla", "gender": "F"},
  {"eid": 54, "ename": "Kajol", "gender": "F"},
  {"eid": 55, "ename": "Rani Mukerji", "gender": "F"},
  {"eid": 56, "ename": "Vidya Balan", "gender": "F"},
  {"eid": 57, "ename": "Aishwarya Rai", "gender": "F"},
  {"eid": 58, "ename": "Hema Malini", "gender": "F"},
  {"eid": 59, "ename": "Rekha", "gender": "F"},
  {"eid": 60, "ename": "Shabana Azmi", "gender": "F"},
  {"eid": 61, "ename": "Ayushmann Khurrana", "gender": "M"},
  {"eid": 62, "ename": "Rajkummar Rao", "gender": "M"},
  {"eid": 63, "ename": "Pankaj Tripathi", "gender": "M"},
  {"eid": 64, "ename": "Manoj Bajpayee", "gender": "M"},
  {"eid": 65, "ename": "Nawazuddin Siddiqui", "gender": "M"},
  {"eid": 66, "ename": "Vicky Kaushal", "gender": "M"},
  {"eid": 67, "ename": "Varun Dhawan", "gender": "M"},
  {"eid": 68, "ename": "Tiger Shroff", "gender": "M"},
  {"eid": 69, "ename": "Sidharth Malhotra", "gender": "M"},
  {"eid": 70, "ename": "Arjun Kapoor", "gender": "M"},
  {"eid": 71, "ename": "Sunny Deol", "gender": "M"},
  {"eid": 72, "ename": "Bobby Deol", "gender": "M"},
  {"eid": 73, "ename": "Dharmendra", "gender": "M"},
  {"eid": 74, "ename": "Jackie Shroff", "gender": "M"},
  {"eid": 75, "ename": "Anil Kapoor", "gender": "M"},
  {"eid": 76, "ename": "Riteish Deshmukh", "gender": "M"},
  {"eid": 77, "ename": "Emraan Hashmi", "gender": "M"},
  {"eid": 78, "ename": "John Abraham", "gender": "M"},
  {"eid": 79, "ename": "Sanjay Dutt", "gender": "M"},
  {"eid": 80, "ename": "Farhan Akhtar", "gender": "M"},
  {"eid": 81, "ename": "Kangana Ranaut", "gender": "F"},
  {"eid": 82, "ename": "Bhumi Pednekar", "gender": "F"},
  {"eid": 83, "ename": "Yami Gautam", "gender": "F"},
  {"eid": 84, "ename": "Radhika Apte", "gender": "F"},
  {"eid": 85, "ename": "Konkona Sen Sharma", "gender": "F"},
  {"eid": 86, "ename": "Shreya Ghoshal", "gender": "F"},
  {"eid": 87, "ename": "Sunidhi Chauhan", "gender": "F"},
  {"eid": 88, "ename": "Neha Kakkar", "gender": "F"},
  {"eid": 89, "ename": "Lata Mangeshkar", "gender": "F"},
  {"eid": 90, "ename": "Asha Bhosle", "gender": "F"},
  {"eid": 91, "ename": "Diljit Dosanjh", "gender": "M"},
  {"eid": 92, "ename": "Gippy Grewal", "gender": "M"},
  {"eid": 93, "ename": "Prithviraj Sukumaran", "gender": "M"},
  {"eid": 94, "ename": "Mohanlal", "gender": "M"},
  {"eid": 95, "ename": "Mammootty", "gender": "M"},
  {"eid": 96, "ename": "Fahadh Faasil", "gender": "M"},
  {"eid": 97, "ename": "Yash", "gender": "M"},
  {"eid": 98, "ename": "Darshan", "gender": "M"},
  {"eid": 99, "ename": "Puneeth Rajkumar", "gender": "M"},
  {"eid": 100, "ename": "Rakshit Shetty", "gender": "M"}
]
#collect all male employees into new list.
male_employees=[]

for employee in employees:
    if employee["gender"]== "male":
        male_employees.append(employee)

print("no of male employees:",len(male_employees))